name: CI
on:
  workflow_dispatch:
    inputs: {}

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update nightly && rustup default nightly
    - run: cargo build
    - name: Configure crates.io token
      run: |
        echo "[registry]" >> $HOME/.cargo/credentials
        echo "token = \"${{ secrets.CRATESIO_TOKEN }}\"" >> $HOME/.cargo/credentials
    - run: cargo run ${{ secrets.github_token }} "0.0.$(date +%Y%m%d)"
      if: github.event_name != 'pull_request'

