name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    # every tuesday at 8am run the build
    - cron: "0 8 * * 2"

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - run: cargo build
      - name: Configure crates.io token
        run: |
          echo "[registry]" >> $HOME/.cargo/credentials
          echo "token = \"${{ secrets.CRATESIO_TOKEN }}\"" >> $HOME/.cargo/credentials
        if: github.event_name != 'pull_request'
      - run: cargo run ${{ secrets.GH_TOKEN }}
        if: github.event_name != 'pull_request'
