name: CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: '0.0.20220103'

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update nightly && rustup default nightly
    - run: cargo build
    - name: Configure crates.io token
      run: |
        echo "[registry]" >> $HOME/.cargo/credentials
        echo "token = \"${{ secrets.CRATESIO_TOKEN }}\"" >> $HOME/.cargo/credentials
        echo ${{ github.events.input.version }}
    - run: cargo run ${{ secrets.github_token }} ${{ github.events.input.version }}
      if: github.event_name != 'pull_request'

