name: CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Version'     
        required: true
        default: 'warning'
      tags:
        description: 'A new release'

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update nightly && rustup default nightly
    - run: cargo build
    - name: Configure crates.io token
      run: |
        echo "[registry]" >> $HOME/.cargo/credentials
        echo "token = \"${{ secrets.CRATESIO_TOKEN }}\"" >> $HOME/.cargo/credentials
    - run: cargo run ${{ secrets.github_token }}
      if: github.event_name != 'pull_request'

