name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Once a day at 8am run the build
    - cron:  '0 8 * * *'

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly
        echo "##[add-path]$HOME/.cargo/bin"
    - run: cargo build
    - name: Configure crates.io token
      run: |
        echo "[registry]" >> $HOME/.cargo/credentials
        echo "token = \"${{ secrets.CRATESIO_TOKEN }}\"" >> $HOME/.cargo/credentials
    - run: cargo run ${{ secrets.github_token }}
      if: github.event_name != 'pull_request'

